def process_issue(issue, repo, rag_loop, parse_code_changes):
    # ... (rest of the process_issue function) ...

def process_pull_request_comment(pr, comment, repo, rag_loop, parse_code_changes):
    # ... (rest of the process_pull_request_comment function) ...