BEGIN_FILE_TAG = '<!-- BEGIN FILE PATH="{}" -->'
END_FILE_TAG = '<!-- END FILE PATH="{}" -->'
SPECIAL_BEGIN_FILE_CONTENTS_DELIMETER = '<!-- BEGIN FILE CONTENTS -->'
SPECIAL_END_FILE_CONTENTS_DELIMETER = '<!-- END FILE CONTENTS -->'